name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud 🔑
      uses: google-github-actions/auth@v1.1.0
      with:
        credentials_json: '${{ secrets.GOOGLE }}'

    - name: Authenticate to Google Artifact Registry 🔑
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ vars.LOCATION }}-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GOOGLE }}

    - name: Build and Push Container 🏗️
      run: |-
        IMAGE=${{ vars.LOCATION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE }}:${{ github.sha }}
        docker build -t $IMAGE \
          --build-arg GITHUB=${{ secrets.GITHUB }} \
          --build-arg WEBHOOK=${{ secrets.WEBHOOK }} \
          --build-arg CAPTCHA_PUBLIC=${{ secrets.CAPTCHA_PUBLIC }} \
          --build-arg CAPTCHA_PRIVATE=${{ secrets.CAPTCHA_PRIVATE }} ./
        docker push $IMAGE

    - name: Cleanup Google Artifact Registry 🧹
      run: |-
        SERVICE=${{ vars.LOCATION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE }}
        DIGESTS=$(gcloud artifacts docker images list $SERVICE --sort-by=update_time --format='value(DIGEST)' | head -n -1)
        while read -r DIGEST; do gcloud artifacts docker images delete "$SERVICE@$DIGEST" --delete-tags --quiet; done <<< $DIGESTS
