name: Build and Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Authenticate to the Registry 🔑
      run: echo '${{ secrets.REGISTRY_PASSWORD }}' | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

    - name: Build and Push Container 🏗️
      run: |-
        REPO=${{ secrets.REGISTRY_URL }}/${{ vars.SERVICE }}
        IMAGE=$REPO:${{ github.sha }}
        docker build -t $IMAGE \
          --build-arg GITHUB=${{ secrets.GITHUB }} \
          --build-arg WEBHOOK=${{ secrets.WEBHOOK }} \
          --build-arg TURNSTILE_PUBLIC=${{ secrets.TURNSTILE_PUBLIC }} \
          --build-arg TURNSTILE_PRIVATE=${{ secrets.TURNSTILE_PRIVATE }} ./
        docker tag $IMAGE $REPO:latest
        docker push $REPO:latest

    - name: Deploy 🚀
      run: |-
        curl ${{ secrets.CD_URL }}/${{ vars.SERVICE }} -H 'authorization: ${{ secrets.CD_AUTHORIZATION }}'

    # - name: Cleanup the Registry 🧹
    #   run: |-
