name: Build and Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    - name: Set up Docker Buildx ⚓
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to the Registry 🔑
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Container 🏗️
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ vars.SERVICE }}:latest
        cache-from: type=registry,ref=${{ vars.SERVICE }}:buildcache
        cache-to: type=registry,ref=${{ vars.SERVICE }}:buildcache,mode=max
        build-args: |
          PORT=${{ vars.PORT }}
          GITHUB=${{ secrets.GITHUB }}
          WEBHOOK=${{ secrets.WEBHOOK }}
          TURNSTILE_PUBLIC=${{ secrets.TURNSTILE_PUBLIC }}
          TURNSTILE_PRIVATE=${{ secrets.TURNSTILE_PRIVATE }}

    - name: Deploy 🚀
      run: |-
        curl ${{ secrets.CD_URL }}/${{ vars.SERVICE }} -H 'authorization: ${{ secrets.CD_AUTHORIZATION }}'
